# name: Test

# on:
#   push:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: 3.11
#           cache: 'pip'
#       - uses: py-actions/flake8@v2
#         with:
#           path: "./src/"
#       - run: pip install -r requirements.txt
#       - run: ./src/checker.py
